version: "3"

services:
  household-replacement-tracker:
    build: .
    container_name: household-replacement-tracker
    network_mode: host
    volumes:
      - hrt-data:/app/data
    restart: unless-stopped

volumes:
  hrt-data:
    external: true
